export const GreenCP = [
  {
    Name: "Angler's Instincts",
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases your chance of catching higher quality fish, akin to fishing with another player. This effect can stack with other similar bonuses.',
  },
  {
    Name: 'Breakfall',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces your fall damage taken by 7% per stage.',
  },
  {
    Name: "Cutpurse's Art",
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases the chance to get higher-quality loot when pickpocketing.',
  },
  {
    Name: 'Fade Away',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Escaping from a Guard wipes 25% of your current Heat, but not Bounty.',
  },
  {
    Name: 'Fleet Phantom',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces the Movement Speed penalty of Sneak by 5% per stage.',
  },
  {
    Name: "Fortune's Favor",
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases the amount of gold you find in treasure chests and safeboxes by 10% per stage.',
  },
  {
    Name: 'Friends in Low Places',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Removes 1000 gold from your bounty once per day when committing a crime where bounty is added. You must be level 50 for this passive to activate, and your current bounty must be at or greater than 1000 gold.',
  },
  {
    Name: 'Gifted Rider',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases your Mount Speed by 2% per stage.',
  },
  {
    Name: 'Gilded Fingers',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases your gold gained by 2% per stage.',
  },
  {
    Name: '',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: '',
  },
  {
    Name: '',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: '',
  },
  {
    Name: 'Homemaker',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'You have a 10% chance to find a second furnishing plan whenever you find a furnishing plan in the world.',
  },
  {
    Name: 'Infamous',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases the value of fenced items by 25%.',
  },
  {
    Name: 'Inspiration Boost',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases your crafting inspiration gained by 10% per stage.',
  },
  {
    Name: 'Liquid Efficiency',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Whenever you use a potion or poison you have a 10% chance to not consume it.',
  },
  {
    Name: 'Master Gatherer',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces the time it takes to harvest by 10% per stage.',
  },
  {
    Name: 'Meticulous Disassembly',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Improves the chances of extracting Woodworking, Blacksmithing, Clothing, and Jewelry Crafting ingredients and allows the refining of more powerful resins, tempers, tannins, and platings from raw materials.',
  },
  {
    Name: 'Out of Sight',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces the radius you can be detected while Sneaking by 1 meter per stage.',
  },
  {
    Name: 'Plentiful Harvest',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'You have a 10% chance to gain double the yield from normal resource nodes per stage.',
  },
  {
    Name: 'Professional Upkeep',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces the cost of repairing your armor by 1% per stage.',
  },
  {
    Name: 'Rationer',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Adds 10 minutes to the duration of any food or drink that increases your character's stats per stage.',
  },
  {
    Name: 'Reel Technique',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Decreases the time it takes for a fish to bite by 25%.',
  },
  {
    Name: 'Shadowstrike',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'When you kill an enemy with Blade of Woe, you become invisible for 5 seconds after a short delay while distracting nearby enemies or potential witnesses. While under this effect you can cast Blade of Woe.',
  },
  {
    Name: 'Soul Reservoir',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'When you resurrect yourself or another player you have a 33% chance to not consume a Soul Gem.',
  },
  {
    Name: 'Steadfast Enchantment',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Your Weapon Enchantments have a 10% chance to not consume a charge when activated per stage.',
  },
  {
    Name: "Steed's Blessing",
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increases your out of combat Movement Speed by .4% per stage.',
  },
  {
    Name: 'Sustaining Shadows',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces the cost of Sneak by 1% per stage.',
  },
  {
    Name: 'Treasure Hunter',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Increase the quality of items you find in treasure chests.',
  },
  {
    Name: 'Wanderer',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Reduces the cost of Wayshrine usage by 10% per stage.',
  },
  {
    Name: 'War Mount',
    Type: 'Craft Tree',
    Area: 'Main',
    Effect: 'Improves your mastery with mounts, removing all mount Stamina costs outside of combat.',
  }
];
